### ISSUE TITLE
Search includes non existing attributes

### ISSUE THREAD

**Issue by kp-intension** [spring-projects/spring-data-ldap#240] opened 2021-02-10 09:57 UTC
I'm getting wierd logs in the Oracle Unified Directory, when I searching for an entry. 
I use the "new way" like it is described [here](https://www.baeldung.com/spring-data-ldap) to search for an entry. The resulting search request contains a bunch of attributes (named "java*") that are not defined in the entity we are looking for.  I didn't find an explanation when or why these attributes are added to the search request. I debugged it as deep as I could get and constantly all the way through the code the variable, which holds the attributes to search for, doesn't have the non existing attributes (e.g. javaClassName) included.

`[2021-01-27T11:01:19.977+01:00][category: REQ] [base: o=car] [scope: sub] [filter: (&(&(objectclass=tcar)(objectclass=top))(carID=2345))] [attrs: tcar,dn,cn,carID,objectclass,tcreatedAt,objectClass,javaSerializedData,javaClassName,javaFactory,javaCodeBase,javaReferenceAddress,javaClassNames,javaRemoteLocation] SEARCH`

If I use the "old way", create a query with the LdapQueryBuilder and execute a search, the log says that it searches over ALL attributes.

`[2021-01-27T11:01:20.452+01:00][category: REQ] [base: o=car] [scope: sub] [filter: (&(&(objectclass=tcar)(objectclass=top))(carID=2345))] [attrs: ALL] SEARCH`

Now I don't know if it is a bug in the framework, I configured something wrong or it has something to do with the Oracle Unified Directory. Could anybody please help me?

**Comment by mp911de** [comment] 2021-02-10 12:18
Can you provide the domain class along the repository declaration or a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem?

**Comment by kp-intension** [comment] 2021-02-11 08:31
Hi mp911de,
thanks for the quick response. Here ist the minimal sample:

<pre>
// entity class
@Entry(base = "o=car", objectClasses = {"tcar", "top"})
public final class Car
{
    @Id
    private Name    dn;

    @DnAttribute(value = "cn", index = 1)
    private String  cn;

    private Integer carID;

    private String tcreatedAt;
}

// repo class
@Repository
public interface CarRepository
    extends LdapRepository<Car>
{
    Optional<Car> findByWiwID(Integer carID);
}

// test class
class CarTest
{
    @Autowired
    private CarRepository carRepository;

    @Test
    void test()
        throws Exception
    {
	carRepository.findByWiwID(13145);
    }
}
<code>

**Comment by mp911de** [comment] 2021-02-18 09:02
`tcar,dn,cn,carID,objectclass,tcreatedAt,objectClass` are derived from the given Java class. 

`javaSerializedData,javaClassName,javaFactory,javaCodeBase,javaReferenceAddress,javaClassNames,javaRemoteLocation` seem to originate from your LDAP server.

**Comment by kp-intension** [comment] 2021-02-18 12:34
I did some more research the last days and I think it has to do with the required attributes articulated in Open-source Oracle's code in /com/sun/jndi/ldap/Obj.java as you can see [here](http://www.docjar.com/html/api/com/sun/jndi/ldap/Obj.java.html)
There is something in between the "old" and the "new" way of the spring-data-ldap search, which uses the JNDI in a different way.
I'm also a little bit confused that it only happens when searching and not when writing an entry. It would be more logical if both were in sync.
What do you think?

**Comment by mp911de** [comment] 2021-02-18 13:10
I don't understand what you mean with new and old way of Spring Data LDAP search. Spring Data LDAP and Spring LDAP haven't changed since the past 6 months.

**Comment by kp-intension** [comment] 2021-02-19 07:12
Ok, sorry for the misunderstanding. Just to clarify it: The "old way" is spring-ldap, where the search is executed over the ldapTemplate. With spring-ldap it is fine like I wrote in the first comment 8 days ago.

If I build a query manually with the LdapQueryBuilder and execute a search, the log says that it searches over all attributes. `ALL` in the log means that, it searches for all existing attributes.
`[2021-01-27T11:01:20.452+01:00][category: REQ] [base: o=car] [scope: sub] [filter: (&(&(objectclass=tcar)(objectclass=top))(carID=2345))] [attrs: ALL] SEARCH`

In spring-data-ldap the repository method `findByCarID` searches for all attributes, which are defined in the Car entity and additionally for the JAVA_ATTRIBUTES from the Obj.java class.

I hope it is more understandable now.

**Comment by mp911de** [comment] 2021-02-19 07:24
Thanks a lot. I'm not sure why attributes from the `Obj` class get added to the query. Is your domain model subclassing `Obj`? If so, then that would be the answer to this question.

**Comment by kp-intension** [comment] 2021-02-19 10:04
Of course subclassing Obj would explain the attributes. But as you can see from the minimal sample the domain model does not subclass Obj. This is why we don't understand the origin of these attributes.

**Comment by mp911de** [comment] 2021-02-19 10:35
Since I cannot reproduce the issue, I suggest debugging `LdapTemplate.find(…)` specifically where `manageClass(clazz)` is called. That's the call that controls which attributes to return.

**Comment by kp-intension** [comment] 2021-02-22 15:50
We spend more time and debugged it once again and went deeper into the `DefaultObjectDirectoryMapper.mapFromLdapDataEntry(...)` implementation, but non of the strange attributes were added. We additionally changed the Java version, used another LDAP (389ds-basic) and dropped the Lombok annotations out of the model class.

But unfortunately the log from 389ds-basic is:

`[22/Feb/2021:13:50:55.243031537 +0000] conn=11 op=1 SRCH base="o=car" scope=2 filter="(&(&(objectClass=tcar)(objectClass=top))(carID=2345))" attrs="tcar dn cn carID objectClass tcreatedAt objectClass javaSerializedData javaClassName javaFactory javaCodebase javaReferenceAddress javaClassNames javaremotelocation"`

We have two independent LDAPs, which logs the same not existing attributes, but at this point we are clueless and will not make further efforts to analyse it.

**Comment by mp911de** [comment] 2021-02-23 08:26
That's indeed strange. Since the `LdapTemplate` isn't adding these attributes it must relate to some inner mechanics of either the LDAP connector or the LDAP directory service itself. Both are out of the scope of where we can assist.

We're going to close this ticket since it isn't actionable. Let us know if there's something we can assist you within of Spring Data LDAP or Spring LDAP.

**Closed by mp911de** 2021-02-23 08:26 UTC
Labels: status: feedback-provided

**Comment by jgosmann** [comment] 2022-04-19 12:02
We are seeing similar behavior with an update from spring-ldap-core from version 2.3.0 to version 2.3.1 (or higher): undesired and non-existent `java*` attributes are queried from the LDAP.

[This is the change the triggers this.](https://github.com/spring-projects/spring-ldap/pull/425/files#diff-2a0d3057d7a72c66d12124ef579a7fdabc1d52d18699e0fe90d2c1aaac3e4645R1834) Note that it sets the returning attributes which were previously left undefined (I assume meaning that all are returned). [This has some interaction with the `LdapCtx` class in the JDK.](https://github.com/openjdk/jdk/blob/jdk8-b120/jdk/src/share/classes/com/sun/jndi/ldap/LdapCtx.java#L1803-L1829) It will query those additional `java*` attributes if an explicit list of attributes is set *and* if an object is requested to be returned. Unfortunately, it is not possible to disable this flag because [it is always set by spring-ldap-core in `LdapTemplate`](https://github.com/spring-projects/spring-ldap/blob/main/core/src/main/java/org/springframework/ldap/core/LdapTemplate.java#L644). (Also, I'm not sure if it would be desirable to disable/what the implications are.)
